name: CI Full Stack

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Static analysis (Checkstyle, PMD, SpotBugs)
        working-directory: backend-clinica
        run: mvn verify -DskipTests=true

      - name: Unit tests
        working-directory: backend-clinica
        run: mvn test -Dtest=*ServiceTest

      - name: Integration tests
        working-directory: backend-clinica
        run: mvn test -Dtest=*IntegrationTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: backend-clinica/target/surefire-reports

  test-frontend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: frontend-clinica

      - name: Run ESLint
        run: npm run lint
        working-directory: frontend-clinica

      - name: Run Stylelint
        run: npm run stylelint
        working-directory: frontend-clinica

      - name: Check formatting (Prettier)
        run: npm run format:check
        working-directory: frontend-clinica
